// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package releaseswatcher

import (
	"context"
	"fmt"
	"github.com/joho/godotenv"
	"os"
)

// Injectors from wire.go:

func initializeApp(ctx context.Context, connection ConnectionString, token MusicBrainzToken, root RootPath, spreadsheetID SpreadsheetID, credentialsFile GoogleCredentialsFile) (Application, error) {
	pool, err := NewPgxPool(ctx, connection)
	if err != nil {
		return Application{}, err
	}
	db, err := NewDB(pool)
	if err != nil {
		return Application{}, err
	}
	cache := NewCache(pool)
	musicBrainzLibrary, err := NewMusicBrainzLibrary(token, db, cache)
	if err != nil {
		return Application{}, err
	}
	watcher, err := NewWatcher(root, db, musicBrainzLibrary)
	if err != nil {
		return Application{}, err
	}
	differ := NewDiffer(db)
	artistSettingsSheet, err := NewArtistSettingsSheet(ctx, spreadsheetID, credentialsFile)
	if err != nil {
		return Application{}, err
	}
	application := NewApplication(db, watcher, differ, artistSettingsSheet)
	return application, nil
}

// wire.go:

type Application struct {
	DB             DB
	Watcher        Watcher
	Differ         Differ
	ArtistSettings ArtistSettingsSheet
}

func NewApplication(
	db DB,
	watcher Watcher,
	differ Differ,
	artistSettings ArtistSettingsSheet,
) Application {
	return Application{
		DB:             db,
		Watcher:        watcher,
		Differ:         differ,
		ArtistSettings: artistSettings,
	}
}

func InitializeApplication(ctx context.Context) (Application, error) {
	err := godotenv.Load()
	if err != nil {
		return Application{}, fmt.Errorf("error loading .env file: %w", err)
	}

	connectionString := ConnectionString(os.Getenv("PGCONNECTION"))
	if connectionString == "" {
		return Application{}, fmt.Errorf("provide a connection string PGCONNECTION")
	}
	musicbrainzToken := MusicBrainzToken(os.Getenv("MUSICBRAINZ_TOKEN"))
	if musicbrainzToken == "" {
		return Application{}, fmt.Errorf("provide a MUSICBRAINZ_TOKEN")
	}
	root := RootPath(os.Getenv("ROOT"))
	if root == "" {
		return Application{}, fmt.Errorf("provide a ROOT")
	}

	credentialsFile := GoogleCredentialsFile(os.Getenv("GOOGLE_APPLICATION_CREDENTIALS"))

	spreadsheetID := SpreadsheetID(os.Getenv("GOOGLE_SHEETS_SPREADSHEET_ID"))

	app, err := initializeApp(ctx, connectionString, musicbrainzToken, root, spreadsheetID, credentialsFile)
	if err != nil {
		return Application{}, fmt.Errorf("app initialization error: %w", err)
	}

	return app, nil
}
